-- ============================================================================
-- V1__baseline.sql
-- Modular ERP - Complete database schema baseline migration
-- PostgreSQL syntax
-- ============================================================================

-- ============================================================================
-- PLATFORM: ADMIN
-- ============================================================================

-- Tenants (extends BaseEntity, NOT TenantEntity)
CREATE TABLE IF NOT EXISTS tenants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(50) NOT NULL,
    name            VARCHAR(200) NOT NULL,
    description     VARCHAR(500),
    plan            VARCHAR(20) NOT NULL DEFAULT 'FREE',
    max_users       INT NOT NULL DEFAULT 10,
    max_storage_mb  BIGINT NOT NULL DEFAULT 1024,
    settings        TEXT,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    activated_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_tenants_tenant_id UNIQUE (tenant_id)
);

-- ============================================================================
-- PLATFORM: SECURITY
-- ============================================================================

-- Users (extends TenantEntity)
CREATE TABLE IF NOT EXISTS users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    login_id        VARCHAR(50) NOT NULL,
    password        VARCHAR(255) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    email           VARCHAR(200),
    locale          VARCHAR(5) DEFAULT 'ko',
    CONSTRAINT uq_users_tenant_login UNIQUE (tenant_id, login_id)
);
CREATE INDEX IF NOT EXISTS idx_users_tenant ON users (tenant_id);

-- User roles (ElementCollection)
CREATE TABLE IF NOT EXISTS user_roles (
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role            VARCHAR(255) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_user_roles_user ON user_roles (user_id);

-- ============================================================================
-- PLATFORM: ADMIN - RBAC
-- ============================================================================

-- Roles (extends TenantEntity)
CREATE TABLE IF NOT EXISTS roles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    role_code       VARCHAR(50) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    is_system       BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_roles_tenant_code UNIQUE (tenant_id, role_code)
);
CREATE INDEX IF NOT EXISTS idx_roles_tenant ON roles (tenant_id);

-- Permissions (extends BaseEntity)
CREATE TABLE IF NOT EXISTS permissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    role_id         BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    resource        VARCHAR(100) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_permissions_role ON permissions (role_id);

-- Permission actions (ElementCollection)
CREATE TABLE IF NOT EXISTS permission_actions (
    permission_id   BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    action          VARCHAR(255) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_permission_actions_perm ON permission_actions (permission_id);

-- ============================================================================
-- PLATFORM: ADMIN - Menu Profiles
-- ============================================================================

-- Menu profiles (extends TenantEntity)
CREATE TABLE IF NOT EXISTS menu_profiles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    profile_code    VARCHAR(50) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    CONSTRAINT uq_menu_profiles_tenant_code UNIQUE (tenant_id, profile_code)
);
CREATE INDEX IF NOT EXISTS idx_menu_profiles_tenant ON menu_profiles (tenant_id);

-- Menu profile items (extends BaseEntity)
CREATE TABLE IF NOT EXISTS menu_profile_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    profile_id      BIGINT NOT NULL REFERENCES menu_profiles(id) ON DELETE CASCADE,
    menu_code       VARCHAR(100) NOT NULL,
    sort_order      INT NOT NULL DEFAULT 0,
    visible         BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE INDEX IF NOT EXISTS idx_menu_profile_items_profile ON menu_profile_items (profile_id);

-- ============================================================================
-- PLATFORM: ADMIN - System Codes
-- ============================================================================

-- System codes (extends TenantEntity)
CREATE TABLE IF NOT EXISTS system_codes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    group_code      VARCHAR(50) NOT NULL,
    group_name      VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    is_system       BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_system_codes_tenant_group UNIQUE (tenant_id, group_code)
);
CREATE INDEX IF NOT EXISTS idx_system_codes_tenant ON system_codes (tenant_id);

-- System code items (extends BaseEntity)
CREATE TABLE IF NOT EXISTS system_code_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    system_code_id  BIGINT NOT NULL REFERENCES system_codes(id) ON DELETE CASCADE,
    code            VARCHAR(50) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    sort_order      INT NOT NULL DEFAULT 0,
    extra           VARCHAR(2000)
);
CREATE INDEX IF NOT EXISTS idx_system_code_items_parent ON system_code_items (system_code_id);

-- ============================================================================
-- PLATFORM: ADMIN - Organizations
-- ============================================================================

-- Organizations (extends TenantEntity)
CREATE TABLE IF NOT EXISTS organizations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    code            VARCHAR(50) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    org_type        VARCHAR(20) NOT NULL,
    parent_id       BIGINT REFERENCES organizations(id),
    sort_order      INT NOT NULL DEFAULT 0,
    description     VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_organizations_tenant ON organizations (tenant_id);
CREATE INDEX IF NOT EXISTS idx_organizations_parent ON organizations (parent_id);

-- ============================================================================
-- PLATFORM: ADMIN - Field Permissions
-- ============================================================================

-- Field permissions (extends TenantEntity)
CREATE TABLE IF NOT EXISTS field_permissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    role_code       VARCHAR(50) NOT NULL,
    resource        VARCHAR(100) NOT NULL,
    field_name      VARCHAR(100) NOT NULL,
    access_level    VARCHAR(20) NOT NULL,
    CONSTRAINT uq_field_perms_tenant_role_res_field UNIQUE (tenant_id, role_code, resource, field_name)
);
CREATE INDEX IF NOT EXISTS idx_field_permissions_tenant ON field_permissions (tenant_id);

-- ============================================================================
-- PLATFORM: ADMIN - Data Scopes
-- ============================================================================

-- Data scopes (extends TenantEntity)
CREATE TABLE IF NOT EXISTS data_scopes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    role_code       VARCHAR(50) NOT NULL,
    resource        VARCHAR(100) NOT NULL,
    scope_type      VARCHAR(20) NOT NULL,
    scope_values    VARCHAR(2000),
    CONSTRAINT uq_data_scopes_tenant_role_res_type UNIQUE (tenant_id, role_code, resource, scope_type)
);
CREATE INDEX IF NOT EXISTS idx_data_scopes_tenant ON data_scopes (tenant_id);

-- ============================================================================
-- PLATFORM: ADMIN - API Keys
-- ============================================================================

-- API keys (extends TenantEntity)
CREATE TABLE IF NOT EXISTS api_keys (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    name                VARCHAR(100) NOT NULL,
    key_hash            VARCHAR(64) NOT NULL,
    key_prefix          VARCHAR(8) NOT NULL,
    description         VARCHAR(500),
    allowed_resources   VARCHAR(2000),
    rate_limit          INT,
    expires_at          TIMESTAMP WITH TIME ZONE,
    last_used_at        TIMESTAMP WITH TIME ZONE,
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uq_api_keys_key_hash UNIQUE (key_hash)
);
CREATE INDEX IF NOT EXISTS idx_api_keys_tenant ON api_keys (tenant_id);

-- ============================================================================
-- PLATFORM: AUDIT
-- ============================================================================

-- Audit logs (standalone, not extending BaseEntity)
CREATE TABLE IF NOT EXISTS audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       VARCHAR(50) NOT NULL,
    user_id         VARCHAR(50) NOT NULL,
    action          VARCHAR(20) NOT NULL,
    entity_type     VARCHAR(100) NOT NULL,
    entity_id       VARCHAR(50),
    old_value       TEXT,
    new_value       TEXT,
    ip_address      VARCHAR(45),
    metadata        TEXT,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_audit_tenant_time ON audit_logs (tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_user ON audit_logs (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs (entity_type, entity_id);

-- ============================================================================
-- PLATFORM: PREFERENCES
-- ============================================================================

-- User preferences (extends BaseEntity)
CREATE TABLE IF NOT EXISTS user_preferences (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    user_id         VARCHAR(50) NOT NULL,
    tenant_id       VARCHAR(50) NOT NULL,
    category        VARCHAR(30) NOT NULL,
    preference_key  VARCHAR(100) NOT NULL,
    preference_value VARCHAR(4000) NOT NULL,
    CONSTRAINT uq_user_prefs_user_cat_key UNIQUE (user_id, category, preference_key)
);
CREATE INDEX IF NOT EXISTS idx_user_preferences_user ON user_preferences (user_id);

-- User grid preferences (extends BaseEntity)
CREATE TABLE IF NOT EXISTS user_grid_preferences (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    user_id         VARCHAR(50) NOT NULL,
    tenant_id       VARCHAR(50) NOT NULL,
    grid_id         VARCHAR(100) NOT NULL,
    column_state    TEXT,
    sort_model      TEXT,
    filter_model    TEXT,
    page_size       INT DEFAULT 20,
    CONSTRAINT uq_user_grid_prefs_user_grid UNIQUE (user_id, grid_id)
);
CREATE INDEX IF NOT EXISTS idx_user_grid_prefs_user ON user_grid_preferences (user_id);

-- ============================================================================
-- MODULE: MASTER DATA
-- ============================================================================

-- Items (extends TenantEntity)
CREATE TABLE IF NOT EXISTS items (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at                      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by                      VARCHAR(255),
    updated_by                      VARCHAR(255),
    active                          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id                       VARCHAR(255) NOT NULL,
    code                            VARCHAR(50) NOT NULL,
    item_type                       VARCHAR(20) NOT NULL DEFAULT 'MATERIAL',
    item_group                      VARCHAR(50),
    unit_of_measure                 VARCHAR(10) NOT NULL DEFAULT 'EA',
    specification                   VARCHAR(100),
    weight                          NUMERIC(12,4),
    volume                          NUMERIC(12,4),
    maker_name                      VARCHAR(50),
    maker_item_no                   VARCHAR(50),
    quality_inspection_required     BOOLEAN NOT NULL DEFAULT FALSE,
    phantom_bom                     BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_items_tenant_code UNIQUE (tenant_id, code)
);
CREATE INDEX IF NOT EXISTS idx_items_tenant ON items (tenant_id);

-- Item translations (EmbeddedId: entity_id + locale)
CREATE TABLE IF NOT EXISTS item_translations (
    entity_id       BIGINT NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    locale          VARCHAR(5) NOT NULL,
    name            VARCHAR(200) NOT NULL,
    description     VARCHAR(500),
    PRIMARY KEY (entity_id, locale)
);

-- Companies (extends TenantEntity)
CREATE TABLE IF NOT EXISTS companies (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by                  VARCHAR(255),
    updated_by                  VARCHAR(255),
    active                      BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id                   VARCHAR(255) NOT NULL,
    code                        VARCHAR(20) NOT NULL,
    name                        VARCHAR(200) NOT NULL,
    business_registration_no    VARCHAR(50),
    ceo_name                    VARCHAR(100),
    address                     VARCHAR(500),
    country_code                VARCHAR(5),
    default_currency            VARCHAR(3) DEFAULT 'KRW'
);
CREATE INDEX IF NOT EXISTS idx_companies_tenant ON companies (tenant_id);

-- Plants (extends TenantEntity)
CREATE TABLE IF NOT EXISTS plants (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    code            VARCHAR(20) NOT NULL,
    name            VARCHAR(200) NOT NULL,
    address         VARCHAR(500),
    company_id      BIGINT NOT NULL REFERENCES companies(id)
);
CREATE INDEX IF NOT EXISTS idx_plants_tenant ON plants (tenant_id);
CREATE INDEX IF NOT EXISTS idx_plants_company ON plants (company_id);

-- BOM Headers (extends TenantEntity)
CREATE TABLE IF NOT EXISTS bom_headers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    product_code    VARCHAR(50) NOT NULL,
    product_name    VARCHAR(200) NOT NULL,
    plant_code      VARCHAR(20) NOT NULL,
    revision        VARCHAR(10) NOT NULL DEFAULT '001',
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    base_quantity   NUMERIC(15,4) NOT NULL DEFAULT 1,
    base_unit       VARCHAR(10) NOT NULL DEFAULT 'EA',
    valid_from      DATE DEFAULT CURRENT_DATE,
    valid_to        DATE,
    description     VARCHAR(500),
    CONSTRAINT uq_bom_tenant_product_rev UNIQUE (tenant_id, product_code, revision)
);
CREATE INDEX IF NOT EXISTS idx_bom_headers_tenant ON bom_headers (tenant_id);
CREATE INDEX IF NOT EXISTS idx_bom_headers_tenant_status ON bom_headers (tenant_id, status);

-- BOM Components (extends TenantEntity)
CREATE TABLE IF NOT EXISTS bom_components (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    bom_header_id   BIGINT NOT NULL REFERENCES bom_headers(id) ON DELETE CASCADE,
    item_code       VARCHAR(50) NOT NULL,
    item_name       VARCHAR(200) NOT NULL,
    quantity        NUMERIC(15,6) NOT NULL,
    unit_of_measure VARCHAR(10) NOT NULL DEFAULT 'EA',
    scrap_rate      NUMERIC(5,4) NOT NULL DEFAULT 0,
    phantom         BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order      INT NOT NULL DEFAULT 0,
    operation_no    INT,
    remark          VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_bom_components_header ON bom_components (bom_header_id);
CREATE INDEX IF NOT EXISTS idx_bom_components_tenant ON bom_components (tenant_id);

-- ============================================================================
-- MODULE: DOCUMENT
-- ============================================================================

-- Document sequences (extends TenantEntity)
CREATE TABLE IF NOT EXISTS document_sequences (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    document_type   VARCHAR(20) NOT NULL,
    prefix          VARCHAR(10) NOT NULL,
    period          VARCHAR(10) NOT NULL,
    current_seq     BIGINT NOT NULL DEFAULT 0,
    pad_length      INT NOT NULL DEFAULT 5,
    CONSTRAINT uq_doc_seq_tenant_type_period UNIQUE (tenant_id, document_type, period)
);
CREATE INDEX IF NOT EXISTS idx_doc_sequences_tenant ON document_sequences (tenant_id);

-- ============================================================================
-- MODULE: PURCHASE
-- ============================================================================

-- Purchase requests (extends TenantEntity)
CREATE TABLE IF NOT EXISTS purchase_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    document_no     VARCHAR(30) NOT NULL,
    company_code    VARCHAR(20) NOT NULL,
    plant_code      VARCHAR(20) NOT NULL,
    department_code VARCHAR(20),
    request_date    DATE NOT NULL DEFAULT CURRENT_DATE,
    delivery_date   DATE,
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    pr_type         VARCHAR(20) NOT NULL DEFAULT 'STANDARD',
    description     VARCHAR(500),
    requested_by    VARCHAR(50),
    CONSTRAINT uq_pr_document_no UNIQUE (document_no)
);
CREATE INDEX IF NOT EXISTS idx_pr_tenant ON purchase_requests (tenant_id);
CREATE INDEX IF NOT EXISTS idx_pr_tenant_status ON purchase_requests (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_pr_tenant_docno ON purchase_requests (tenant_id, document_no);

-- Purchase request lines (extends TenantEntity)
CREATE TABLE IF NOT EXISTS purchase_request_lines (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    purchase_request_id BIGINT NOT NULL REFERENCES purchase_requests(id) ON DELETE CASCADE,
    line_no             INT NOT NULL,
    item_code           VARCHAR(50) NOT NULL,
    item_name           VARCHAR(200) NOT NULL,
    quantity            NUMERIC(15,4) NOT NULL,
    unit_of_measure     VARCHAR(10) NOT NULL DEFAULT 'EA',
    unit_price          NUMERIC(19,4) NOT NULL DEFAULT 0,
    specification       VARCHAR(200),
    remark              VARCHAR(500),
    open_quantity       NUMERIC(15,4) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pr_lines_parent ON purchase_request_lines (purchase_request_id);

-- Purchase orders (extends TenantEntity)
CREATE TABLE IF NOT EXISTS purchase_orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    document_no     VARCHAR(30) NOT NULL,
    company_code    VARCHAR(20) NOT NULL,
    plant_code      VARCHAR(20) NOT NULL,
    vendor_code     VARCHAR(50) NOT NULL,
    vendor_name     VARCHAR(200) NOT NULL,
    order_date      DATE NOT NULL DEFAULT CURRENT_DATE,
    delivery_date   DATE,
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    currency_code   VARCHAR(3) DEFAULT 'KRW',
    payment_terms   VARCHAR(500),
    delivery_terms  VARCHAR(500),
    remark          VARCHAR(1000),
    CONSTRAINT uq_po_document_no UNIQUE (document_no)
);
CREATE INDEX IF NOT EXISTS idx_po_tenant ON purchase_orders (tenant_id);
CREATE INDEX IF NOT EXISTS idx_po_tenant_status ON purchase_orders (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_po_tenant_docno ON purchase_orders (tenant_id, document_no);

-- Purchase order lines (extends TenantEntity)
CREATE TABLE IF NOT EXISTS purchase_order_lines (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    purchase_order_id   BIGINT NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    line_no             INT NOT NULL,
    item_code           VARCHAR(50) NOT NULL,
    item_name           VARCHAR(200) NOT NULL,
    quantity            NUMERIC(15,4) NOT NULL,
    unit_of_measure     VARCHAR(10) NOT NULL DEFAULT 'EA',
    unit_price          NUMERIC(19,4) NOT NULL DEFAULT 0,
    tax_rate            NUMERIC(5,4) NOT NULL DEFAULT 0.10,
    specification       VARCHAR(200),
    pr_document_no      VARCHAR(30),
    pr_line_no          INT,
    received_quantity   NUMERIC(15,4) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_po_lines_parent ON purchase_order_lines (purchase_order_id);

-- RFQs (extends TenantEntity)
CREATE TABLE IF NOT EXISTS rfqs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    document_no     VARCHAR(30) NOT NULL,
    company_code    VARCHAR(20) NOT NULL,
    plant_code      VARCHAR(20) NOT NULL,
    issue_date      DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date        DATE,
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    description     VARCHAR(1000),
    CONSTRAINT uq_rfq_document_no UNIQUE (document_no)
);
CREATE INDEX IF NOT EXISTS idx_rfq_tenant ON rfqs (tenant_id);
CREATE INDEX IF NOT EXISTS idx_rfq_tenant_status ON rfqs (tenant_id, status);

-- RFQ lines (extends TenantEntity)
CREATE TABLE IF NOT EXISTS rfq_lines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    rfq_id          BIGINT NOT NULL REFERENCES rfqs(id) ON DELETE CASCADE,
    line_no         INT NOT NULL,
    item_code       VARCHAR(50) NOT NULL,
    item_name       VARCHAR(200) NOT NULL,
    quantity        NUMERIC(15,4) NOT NULL,
    unit_of_measure VARCHAR(10) NOT NULL,
    specification   VARCHAR(200),
    pr_document_no  VARCHAR(30),
    pr_line_no      INT
);
CREATE INDEX IF NOT EXISTS idx_rfq_lines_parent ON rfq_lines (rfq_id);

-- RFQ vendors (extends TenantEntity)
CREATE TABLE IF NOT EXISTS rfq_vendors (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    rfq_id          BIGINT NOT NULL REFERENCES rfqs(id) ON DELETE CASCADE,
    vendor_code     VARCHAR(50) NOT NULL,
    vendor_name     VARCHAR(200) NOT NULL,
    awarded         BOOLEAN NOT NULL DEFAULT FALSE,
    responded_at    TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_rfq_vendors_parent ON rfq_vendors (rfq_id);

-- Quotation lines (extends TenantEntity)
CREATE TABLE IF NOT EXISTS quotation_lines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    rfq_vendor_id   BIGINT NOT NULL REFERENCES rfq_vendors(id) ON DELETE CASCADE,
    rfq_line_no     INT NOT NULL,
    unit_price      NUMERIC(19,4) NOT NULL,
    lead_time_days  INT,
    remark          VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_quotation_lines_vendor ON quotation_lines (rfq_vendor_id);

-- ============================================================================
-- MODULE: SALES
-- ============================================================================

-- Sales orders (extends TenantEntity)
CREATE TABLE IF NOT EXISTS sales_orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    document_no     VARCHAR(30) NOT NULL,
    company_code    VARCHAR(20) NOT NULL,
    plant_code      VARCHAR(20) NOT NULL,
    customer_code   VARCHAR(50) NOT NULL,
    customer_name   VARCHAR(200) NOT NULL,
    order_date      DATE NOT NULL DEFAULT CURRENT_DATE,
    delivery_date   DATE,
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    currency_code   VARCHAR(3) DEFAULT 'KRW',
    payment_terms   VARCHAR(500),
    shipping_address VARCHAR(500),
    remark          VARCHAR(1000),
    CONSTRAINT uq_so_document_no UNIQUE (document_no)
);
CREATE INDEX IF NOT EXISTS idx_so_tenant ON sales_orders (tenant_id);
CREATE INDEX IF NOT EXISTS idx_so_tenant_status ON sales_orders (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_so_tenant_docno ON sales_orders (tenant_id, document_no);

-- Sales order lines (extends TenantEntity)
CREATE TABLE IF NOT EXISTS sales_order_lines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    sales_order_id  BIGINT NOT NULL REFERENCES sales_orders(id) ON DELETE CASCADE,
    line_no         INT NOT NULL,
    item_code       VARCHAR(50) NOT NULL,
    item_name       VARCHAR(200) NOT NULL,
    quantity        NUMERIC(15,4) NOT NULL,
    unit_of_measure VARCHAR(10) NOT NULL DEFAULT 'EA',
    unit_price      NUMERIC(19,4) NOT NULL,
    tax_rate        NUMERIC(5,4) NOT NULL DEFAULT 0.10,
    specification   VARCHAR(200),
    shipped_quantity NUMERIC(15,4) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_so_lines_parent ON sales_order_lines (sales_order_id);

-- ============================================================================
-- MODULE: LOGISTICS
-- ============================================================================

-- Goods receipts (extends TenantEntity)
CREATE TABLE IF NOT EXISTS goods_receipts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    document_no     VARCHAR(30) NOT NULL,
    company_code    VARCHAR(20) NOT NULL,
    plant_code      VARCHAR(20) NOT NULL,
    storage_location VARCHAR(20) NOT NULL,
    po_document_no  VARCHAR(30),
    vendor_code     VARCHAR(50) NOT NULL,
    vendor_name     VARCHAR(200) NOT NULL,
    receipt_date    DATE NOT NULL DEFAULT CURRENT_DATE,
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    remark          VARCHAR(500),
    CONSTRAINT uq_gr_document_no UNIQUE (document_no)
);
CREATE INDEX IF NOT EXISTS idx_gr_tenant ON goods_receipts (tenant_id);
CREATE INDEX IF NOT EXISTS idx_gr_tenant_status ON goods_receipts (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_gr_tenant_docno ON goods_receipts (tenant_id, document_no);

-- Goods receipt lines (extends TenantEntity)
CREATE TABLE IF NOT EXISTS goods_receipt_lines (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by                  VARCHAR(255),
    updated_by                  VARCHAR(255),
    active                      BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id                   VARCHAR(255) NOT NULL,
    goods_receipt_id            BIGINT NOT NULL REFERENCES goods_receipts(id) ON DELETE CASCADE,
    line_no                     INT NOT NULL,
    item_code                   VARCHAR(50) NOT NULL,
    item_name                   VARCHAR(200) NOT NULL,
    quantity                    NUMERIC(15,4) NOT NULL,
    unit_of_measure             VARCHAR(10) NOT NULL,
    unit_price                  NUMERIC(19,4) NOT NULL DEFAULT 0,
    storage_location            VARCHAR(20) NOT NULL,
    po_line_no                  INT,
    quality_inspection_passed   BOOLEAN
);
CREATE INDEX IF NOT EXISTS idx_gr_lines_parent ON goods_receipt_lines (goods_receipt_id);

-- Goods issues (extends TenantEntity)
CREATE TABLE IF NOT EXISTS goods_issues (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    document_no     VARCHAR(30) NOT NULL,
    company_code    VARCHAR(20) NOT NULL,
    plant_code      VARCHAR(20) NOT NULL,
    storage_location VARCHAR(20) NOT NULL,
    issue_type      VARCHAR(20) NOT NULL DEFAULT 'SALES',
    reference_doc_no VARCHAR(30),
    issue_date      DATE NOT NULL DEFAULT CURRENT_DATE,
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    remark          VARCHAR(500),
    CONSTRAINT uq_gi_document_no UNIQUE (document_no)
);
CREATE INDEX IF NOT EXISTS idx_gi_tenant ON goods_issues (tenant_id);
CREATE INDEX IF NOT EXISTS idx_gi_tenant_status ON goods_issues (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_gi_tenant_docno ON goods_issues (tenant_id, document_no);

-- Goods issue lines (extends TenantEntity)
CREATE TABLE IF NOT EXISTS goods_issue_lines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    goods_issue_id  BIGINT NOT NULL REFERENCES goods_issues(id) ON DELETE CASCADE,
    line_no         INT NOT NULL,
    item_code       VARCHAR(50) NOT NULL,
    item_name       VARCHAR(200) NOT NULL,
    quantity        NUMERIC(15,4) NOT NULL,
    unit_of_measure VARCHAR(10) NOT NULL,
    storage_location VARCHAR(20) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_gi_lines_parent ON goods_issue_lines (goods_issue_id);

-- Stock summaries (extends TenantEntity)
CREATE TABLE IF NOT EXISTS stock_summaries (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    item_code           VARCHAR(50) NOT NULL,
    item_name           VARCHAR(200) NOT NULL,
    plant_code          VARCHAR(20) NOT NULL,
    storage_location    VARCHAR(20) NOT NULL,
    unit_of_measure     VARCHAR(10) NOT NULL DEFAULT 'EA',
    quantity_on_hand    NUMERIC(15,4) NOT NULL DEFAULT 0,
    quantity_reserved   NUMERIC(15,4) NOT NULL DEFAULT 0,
    total_value         NUMERIC(19,4) NOT NULL DEFAULT 0,
    CONSTRAINT uq_stock_tenant_item_plant_loc UNIQUE (tenant_id, item_code, plant_code, storage_location)
);
CREATE INDEX IF NOT EXISTS idx_stock_tenant ON stock_summaries (tenant_id);

-- ============================================================================
-- MODULE: PRODUCTION
-- ============================================================================

-- Work centers (extends TenantEntity)
CREATE TABLE IF NOT EXISTS work_centers (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    code            VARCHAR(20) NOT NULL,
    name            VARCHAR(200) NOT NULL,
    plant_code      VARCHAR(20) NOT NULL,
    center_type     VARCHAR(20) NOT NULL DEFAULT 'MACHINE',
    capacity_per_day NUMERIC(5,2) NOT NULL DEFAULT 8.00,
    resource_count  INT NOT NULL DEFAULT 1,
    cost_per_hour   NUMERIC(19,4) NOT NULL DEFAULT 0,
    setup_cost      NUMERIC(19,4) NOT NULL DEFAULT 0,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    description     VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_work_centers_tenant ON work_centers (tenant_id);

-- Routings (extends TenantEntity)
CREATE TABLE IF NOT EXISTS routings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    product_code    VARCHAR(50) NOT NULL,
    product_name    VARCHAR(200) NOT NULL,
    plant_code      VARCHAR(20) NOT NULL,
    revision        VARCHAR(10) NOT NULL DEFAULT '001',
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    description     VARCHAR(500),
    CONSTRAINT uq_routing_tenant_product_plant_rev UNIQUE (tenant_id, product_code, plant_code, revision)
);
CREATE INDEX IF NOT EXISTS idx_routings_tenant ON routings (tenant_id);

-- Routing operations (extends TenantEntity)
CREATE TABLE IF NOT EXISTS routing_operations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    routing_id      BIGINT NOT NULL REFERENCES routings(id) ON DELETE CASCADE,
    operation_no    INT NOT NULL,
    operation_name  VARCHAR(200) NOT NULL,
    work_center_code VARCHAR(20) NOT NULL,
    setup_time      NUMERIC(10,4) NOT NULL DEFAULT 0,
    run_time_per_unit NUMERIC(10,6) NOT NULL,
    description     VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_routing_ops_parent ON routing_operations (routing_id);

-- Work orders (extends TenantEntity)
CREATE TABLE IF NOT EXISTS work_orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    document_no         VARCHAR(30) NOT NULL,
    company_code        VARCHAR(20) NOT NULL,
    plant_code          VARCHAR(20) NOT NULL,
    product_code        VARCHAR(50) NOT NULL,
    product_name        VARCHAR(200) NOT NULL,
    planned_quantity    NUMERIC(15,4) NOT NULL,
    unit_of_measure     VARCHAR(10) NOT NULL DEFAULT 'EA',
    status              VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    order_type          VARCHAR(20) NOT NULL DEFAULT 'STANDARD',
    sales_order_no      VARCHAR(30),
    planned_start_date  DATE,
    planned_end_date    DATE,
    actual_start_date   TIMESTAMP,
    actual_end_date     TIMESTAMP,
    bom_revision        VARCHAR(10),
    routing_revision    VARCHAR(10),
    priority            VARCHAR(10) NOT NULL DEFAULT 'NORMAL',
    remark              VARCHAR(1000),
    completed_quantity  NUMERIC(15,4) NOT NULL DEFAULT 0,
    scrap_quantity      NUMERIC(15,4) NOT NULL DEFAULT 0,
    CONSTRAINT uq_wo_document_no UNIQUE (document_no)
);
CREATE INDEX IF NOT EXISTS idx_wo_tenant ON work_orders (tenant_id);
CREATE INDEX IF NOT EXISTS idx_wo_tenant_status ON work_orders (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_wo_tenant_docno ON work_orders (tenant_id, document_no);

-- Work order operations (extends TenantEntity)
CREATE TABLE IF NOT EXISTS work_order_operations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    work_order_id       BIGINT NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,
    operation_no        INT NOT NULL,
    operation_name      VARCHAR(200) NOT NULL,
    work_center_code    VARCHAR(20) NOT NULL,
    setup_time          NUMERIC(10,4) NOT NULL DEFAULT 0,
    run_time_per_unit   NUMERIC(10,6) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    actual_setup_time   NUMERIC(10,4),
    actual_run_time     NUMERIC(10,4),
    completed_quantity  NUMERIC(15,4) NOT NULL DEFAULT 0,
    scrap_quantity      NUMERIC(15,4) NOT NULL DEFAULT 0,
    started_at          TIMESTAMP,
    completed_at        TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_wo_ops_parent ON work_order_operations (work_order_id);

-- Work order materials (extends TenantEntity)
CREATE TABLE IF NOT EXISTS work_order_materials (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    work_order_id       BIGINT NOT NULL REFERENCES work_orders(id) ON DELETE CASCADE,
    item_code           VARCHAR(50) NOT NULL,
    item_name           VARCHAR(200) NOT NULL,
    required_quantity   NUMERIC(15,4) NOT NULL,
    unit_of_measure     VARCHAR(10) NOT NULL,
    operation_no        INT,
    issued_quantity     NUMERIC(15,4) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_wo_materials_parent ON work_order_materials (work_order_id);

-- ============================================================================
-- MODULE: PLANNING
-- ============================================================================

-- MRP runs (extends TenantEntity)
CREATE TABLE IF NOT EXISTS mrp_runs (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by              VARCHAR(255),
    updated_by              VARCHAR(255),
    active                  BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id               VARCHAR(255) NOT NULL,
    plant_code              VARCHAR(20) NOT NULL,
    planning_horizon_days   INT NOT NULL DEFAULT 30,
    status                  VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    executed_at             TIMESTAMP,
    executed_by             VARCHAR(50)
);
CREATE INDEX IF NOT EXISTS idx_mrp_runs_tenant ON mrp_runs (tenant_id);

-- MRP results (extends TenantEntity)
CREATE TABLE IF NOT EXISTS mrp_results (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    mrp_run_id          BIGINT NOT NULL REFERENCES mrp_runs(id) ON DELETE CASCADE,
    item_code           VARCHAR(50) NOT NULL,
    item_name           VARCHAR(200) NOT NULL,
    gross_requirement   NUMERIC(15,4) NOT NULL,
    on_hand_stock       NUMERIC(15,4) NOT NULL,
    scheduled_receipts  NUMERIC(15,4) NOT NULL,
    net_requirement     NUMERIC(15,4) NOT NULL,
    planned_order_qty   NUMERIC(15,4) NOT NULL,
    unit_of_measure     VARCHAR(10) NOT NULL,
    action_type         VARCHAR(20) NOT NULL,
    required_date       DATE,
    generated_doc_no    VARCHAR(30)
);
CREATE INDEX IF NOT EXISTS idx_mrp_results_parent ON mrp_results (mrp_run_id);

-- Production schedules (extends TenantEntity)
CREATE TABLE IF NOT EXISTS production_schedules (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    plant_code          VARCHAR(20) NOT NULL,
    work_center_code    VARCHAR(20) NOT NULL,
    schedule_date       DATE NOT NULL,
    work_order_no       VARCHAR(30),
    product_code        VARCHAR(50) NOT NULL,
    product_name        VARCHAR(200) NOT NULL,
    planned_quantity    NUMERIC(15,4) NOT NULL,
    planned_hours       NUMERIC(10,4) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'PLANNED',
    sequence_no         INT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_prod_sched_tenant ON production_schedules (tenant_id);

-- Capacity plans (extends TenantEntity)
CREATE TABLE IF NOT EXISTS capacity_plans (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    plant_code          VARCHAR(20) NOT NULL,
    work_center_code    VARCHAR(20) NOT NULL,
    work_center_name    VARCHAR(200) NOT NULL,
    plan_date           DATE NOT NULL,
    available_hours     NUMERIC(10,4) NOT NULL,
    planned_load_hours  NUMERIC(10,4) NOT NULL DEFAULT 0,
    actual_hours        NUMERIC(10,4) NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_capacity_plans_tenant ON capacity_plans (tenant_id);

-- ============================================================================
-- MODULE: ACCOUNT
-- ============================================================================

-- Account masters (extends TenantEntity)
CREATE TABLE IF NOT EXISTS account_masters (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    code            VARCHAR(20) NOT NULL,
    name            VARCHAR(200) NOT NULL,
    account_type    VARCHAR(20) NOT NULL,
    account_group   VARCHAR(20) NOT NULL,
    parent_code     VARCHAR(20),
    postable        BOOLEAN NOT NULL DEFAULT TRUE,
    description     VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_account_masters_tenant ON account_masters (tenant_id);

-- Journal entries (extends TenantEntity)
CREATE TABLE IF NOT EXISTS journal_entries (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    document_no         VARCHAR(30) NOT NULL,
    company_code        VARCHAR(20) NOT NULL,
    posting_date        DATE NOT NULL DEFAULT CURRENT_DATE,
    document_date       DATE NOT NULL DEFAULT CURRENT_DATE,
    entry_type          VARCHAR(20) NOT NULL DEFAULT 'MANUAL',
    reference_doc_no    VARCHAR(30),
    reference_doc_type  VARCHAR(20),
    status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    description         VARCHAR(500),
    currency_code       VARCHAR(3) DEFAULT 'KRW',
    CONSTRAINT uq_je_document_no UNIQUE (document_no)
);
CREATE INDEX IF NOT EXISTS idx_je_tenant ON journal_entries (tenant_id);
CREATE INDEX IF NOT EXISTS idx_je_tenant_status ON journal_entries (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_je_tenant_docno ON journal_entries (tenant_id, document_no);

-- Journal entry lines (extends TenantEntity)
CREATE TABLE IF NOT EXISTS journal_entry_lines (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    journal_entry_id    BIGINT NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
    line_no             INT NOT NULL,
    account_code        VARCHAR(20) NOT NULL,
    account_name        VARCHAR(200) NOT NULL,
    debit_amount        NUMERIC(19,4) NOT NULL DEFAULT 0,
    credit_amount       NUMERIC(19,4) NOT NULL DEFAULT 0,
    cost_center         VARCHAR(20),
    description         VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_je_lines_parent ON journal_entry_lines (journal_entry_id);

-- ============================================================================
-- MODULE: HR
-- ============================================================================

-- Employees (extends TenantEntity)
CREATE TABLE IF NOT EXISTS employees (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    employee_no         VARCHAR(20) NOT NULL,
    name                VARCHAR(100) NOT NULL,
    company_code        VARCHAR(20) NOT NULL,
    department_code     VARCHAR(20),
    department_name     VARCHAR(100),
    position_title      VARCHAR(50),
    job_title           VARCHAR(50),
    email               VARCHAR(200),
    phone               VARCHAR(20),
    hire_date           DATE,
    termination_date    DATE,
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    CONSTRAINT uq_employee_no UNIQUE (employee_no)
);
CREATE INDEX IF NOT EXISTS idx_employees_tenant ON employees (tenant_id);

-- Departments (extends TenantEntity)
CREATE TABLE IF NOT EXISTS departments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    code            VARCHAR(20) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    company_code    VARCHAR(20) NOT NULL,
    parent_code     VARCHAR(20),
    sort_order      INT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_departments_tenant ON departments (tenant_id);

-- ============================================================================
-- MODULE: QUALITY
-- ============================================================================

-- Quality inspections (extends TenantEntity)
CREATE TABLE IF NOT EXISTS quality_inspections (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    document_no         VARCHAR(30) NOT NULL,
    inspection_type     VARCHAR(20) NOT NULL DEFAULT 'INCOMING',
    reference_doc_no    VARCHAR(30),
    item_code           VARCHAR(50) NOT NULL,
    item_name           VARCHAR(200) NOT NULL,
    plant_code          VARCHAR(20) NOT NULL,
    inspected_quantity  NUMERIC(15,4) NOT NULL,
    accepted_quantity   NUMERIC(15,4),
    rejected_quantity   NUMERIC(15,4),
    inspection_date     DATE NOT NULL DEFAULT CURRENT_DATE,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    result              VARCHAR(20),
    remarks             VARCHAR(1000),
    inspector_id        VARCHAR(50),
    CONSTRAINT uq_qi_document_no UNIQUE (document_no)
);
CREATE INDEX IF NOT EXISTS idx_qi_tenant ON quality_inspections (tenant_id);
CREATE INDEX IF NOT EXISTS idx_qi_tenant_status ON quality_inspections (tenant_id, status);

-- ============================================================================
-- MODULE: SUPPLY CHAIN
-- ============================================================================

-- Supplier evaluations (extends TenantEntity)
CREATE TABLE IF NOT EXISTS supplier_evaluations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    vendor_code         VARCHAR(50) NOT NULL,
    vendor_name         VARCHAR(200) NOT NULL,
    evaluation_period   VARCHAR(10) NOT NULL,
    quality_score       NUMERIC(5,2) NOT NULL DEFAULT 0,
    delivery_score      NUMERIC(5,2) NOT NULL DEFAULT 0,
    price_score         NUMERIC(5,2) NOT NULL DEFAULT 0,
    service_score       NUMERIC(5,2) NOT NULL DEFAULT 0,
    grade               VARCHAR(5) NOT NULL DEFAULT 'C',
    evaluation_date     DATE DEFAULT CURRENT_DATE,
    remarks             VARCHAR(1000)
);
CREATE INDEX IF NOT EXISTS idx_supplier_eval_tenant ON supplier_evaluations (tenant_id);

-- ============================================================================
-- MODULE: CONTRACT
-- ============================================================================

-- Contracts (extends TenantEntity)
CREATE TABLE IF NOT EXISTS contracts (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id           VARCHAR(255) NOT NULL,
    document_no         VARCHAR(30) NOT NULL,
    title               VARCHAR(200) NOT NULL,
    contract_type       VARCHAR(20) NOT NULL,
    counterparty_code   VARCHAR(50) NOT NULL,
    counterparty_name   VARCHAR(200) NOT NULL,
    start_date          DATE NOT NULL,
    end_date            DATE NOT NULL,
    contract_amount     NUMERIC(19,4),
    currency_code       VARCHAR(3) DEFAULT 'KRW',
    status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    terms               VARCHAR(2000),
    description         VARCHAR(1000),
    CONSTRAINT uq_contract_document_no UNIQUE (document_no)
);
CREATE INDEX IF NOT EXISTS idx_contracts_tenant ON contracts (tenant_id);
CREATE INDEX IF NOT EXISTS idx_contracts_tenant_status ON contracts (tenant_id, status);

-- ============================================================================
-- MODULE: APPROVAL
-- ============================================================================

-- Approval requests (extends TenantEntity)
CREATE TABLE IF NOT EXISTS approval_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    document_type   VARCHAR(30) NOT NULL,
    document_id     BIGINT NOT NULL,
    requested_by    VARCHAR(255) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    completed_at    TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_approval_requests_tenant ON approval_requests (tenant_id);

-- Approval steps (extends BaseEntity)
CREATE TABLE IF NOT EXISTS approval_steps (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    step_order      INT NOT NULL,
    approver_role   VARCHAR(50) NOT NULL,
    approver_id     VARCHAR(50),
    request_id      BIGINT NOT NULL REFERENCES approval_requests(id) ON DELETE CASCADE,
    decision        VARCHAR(20),
    decided_by      VARCHAR(255),
    decided_at      TIMESTAMP WITH TIME ZONE,
    comment         VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_approval_steps_request ON approval_steps (request_id);

-- Workflow definitions (extends TenantEntity)
CREATE TABLE IF NOT EXISTS workflow_definitions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(255) NOT NULL,
    document_type   VARCHAR(30) NOT NULL,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    version         INT NOT NULL DEFAULT 1,
    is_current      BOOLEAN NOT NULL DEFAULT FALSE,
    designer_layout TEXT,
    CONSTRAINT uq_workflow_tenant_doctype_ver UNIQUE (tenant_id, document_type, version)
);
CREATE INDEX IF NOT EXISTS idx_workflow_defs_tenant ON workflow_definitions (tenant_id);

-- Workflow steps (extends BaseEntity)
CREATE TABLE IF NOT EXISTS workflow_steps (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    active              BOOLEAN NOT NULL DEFAULT TRUE,
    workflow_id         BIGINT NOT NULL REFERENCES workflow_definitions(id) ON DELETE CASCADE,
    step_order          INT NOT NULL,
    name                VARCHAR(100) NOT NULL,
    step_type           VARCHAR(20) NOT NULL,
    approver_type       VARCHAR(20) NOT NULL,
    approver_value      VARCHAR(200) NOT NULL,
    condition           TEXT,
    auto_approve_hours  INT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_workflow_steps_parent ON workflow_steps (workflow_id);
