-- =============================================
-- V6: Enhanced Approval Workflow
-- =============================================

-- Add document_no and step_status columns to existing tables
ALTER TABLE approval_requests ADD COLUMN IF NOT EXISTS document_no VARCHAR(30);
ALTER TABLE approval_steps ADD COLUMN IF NOT EXISTS step_status VARCHAR(20) NOT NULL DEFAULT 'WAITING';

-- Update existing approval_steps decision enum to include RETURNED
-- (PostgreSQL enums are flexible with VARCHAR, no migration needed)

-- ── Approval Delegations ──
CREATE TABLE IF NOT EXISTS approval_delegations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id       VARCHAR(50) NOT NULL,
    from_user_id    VARCHAR(50) NOT NULL,
    to_user_id      VARCHAR(50) NOT NULL,
    start_date      DATE NOT NULL,
    end_date        DATE NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    reason          VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_approval_delegations_tenant ON approval_delegations (tenant_id);
CREATE INDEX IF NOT EXISTS idx_approval_delegations_from ON approval_delegations (tenant_id, from_user_id);
CREATE INDEX IF NOT EXISTS idx_approval_delegations_to ON approval_delegations (tenant_id, to_user_id);

-- ── Approval Comments ──
CREATE TABLE IF NOT EXISTS approval_comments (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    created_by              VARCHAR(255),
    updated_by              VARCHAR(255),
    active                  BOOLEAN NOT NULL DEFAULT TRUE,
    tenant_id               VARCHAR(50) NOT NULL,
    approval_request_id     BIGINT NOT NULL REFERENCES approval_requests(id) ON DELETE CASCADE,
    step_sequence           INT,
    comment_by              VARCHAR(50) NOT NULL,
    comment                 VARCHAR(2000) NOT NULL,
    comment_at              TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_approval_comments_request ON approval_comments (approval_request_id);
CREATE INDEX IF NOT EXISTS idx_approval_comments_tenant ON approval_comments (tenant_id);

-- Add indexes for approval request lookups
CREATE INDEX IF NOT EXISTS idx_approval_requests_doctype ON approval_requests (tenant_id, document_type, document_id);
CREATE INDEX IF NOT EXISTS idx_approval_requests_status ON approval_requests (tenant_id, status);
CREATE INDEX IF NOT EXISTS idx_approval_requests_requester ON approval_requests (tenant_id, requested_by);
CREATE INDEX IF NOT EXISTS idx_approval_steps_status ON approval_steps (step_status);
